#!/bin/sh
APPDIR="$(dirname "$(readlink -f "$0")")"

export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="$APPDIR/usr/share:$XDG_DATA_DIRS"

# This line helps Wayland treat this as an interactive app launch
export QT_WAYLAND_SHELL_INTEGRATION=xdg-shell

exec "$APPDIR/usr/bin/info_overlay_bin" "$@"
