#!/bin/sh
# Get the directory where THIS script is located
APPDIR="$(dirname "$(readlink -f "$0")")"

# Execute the binary using the absolute path derived from the AppDir location
exec "$APPDIR/usr/bin/info_overlay_bin"
